image: $REGISTRY_CI/gitlab-ci-base:buster

stages:
 - test

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:19.03.1-dind

phpunit:
  stage: test
  before_script:
    - docker build -t phpunit .
  script:
    - docker run --rm --name my-running-app phpunit vendor/phpunit/phpunit/phpunit -c tests/phpunit.xml
  allow_failure: false
  tags:
    - gcp-high-load-runner-prod
