image: hipay/gitlab-ci-base:jessie

stages:
 - test

phpunit:
  stage: test
  before_script:
    - docker build -t phpunit .
  script:
    - docker run --rm --name my-running-app phpunit vendor/phpunit/phpunit/phpunit -c tests/phpunit.xml
  allow_failure: false
  tags:
    - pi-ecommerce
